In [ ]:
#Import Pagage Nummpy

In [1]:
import numpy as np

In [ ]:
#Create an array of 10 zeros, 10 ones, 10 fives

In [5]:
array = np.zeros(10)

print("An array of zeros:")
print(array)
array = np.ones(10)
print("An array of ones:")
print(array)
array = np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [ ]:
#Create an array of the integers from 30 to 70

In [17]:
array = np.arange(30,70)
print("Aaray of the intergesr from 30 to 70")
print(array)

Aaray of the intergesr from 30 to 70
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]


In [ ]:
#Create a 3x3 identity matrix

In [20]:
array_2d = np.identity(4)
print("3x3 matrix")
print(array_2d[3])

3x3 matrix
[0. 0. 0. 1.]


In [ ]:
#Create a 3x3 identity matrix

In [30]:
matrix = np.arange(10,22).reshape((3, 4))
print(matrix)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [ ]:
#How to add an extra column

In [42]:
x = np.array([
    [10,20,30],
    [40,50,60]
])
y = np.array([
    [100],
    [200]
])
print(np.append(x, y, axis=1))

[[ 10  20  30 100]
 [ 40  50  60 200]]
